# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('blog', '0011_auto_20180303_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='sidebar_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
