# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180303_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='sidebar_image',
            new_name='header_image',
        ),
    ]
