# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180303_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='name_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='url_1',
            field=models.URLField(null=True),
        ),
    ]
