# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180304_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='url_1',
            field=models.URLField(blank=True, null=True),
        ),
    ]
