# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180304_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='name_1',
            new_name='link_to_page_1',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='url_1',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='page_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
