# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 16:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180304_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='add_page_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='add_page_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='add_page_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='add_page_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='add_page_5',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='add_page_6',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_to_page_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_to_page_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_to_page_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_to_page_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_to_page_5',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_to_page_6',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
